import type { Metadata } from "next";
import { Inter, IBM_Plex_Serif } from "next/font/google";
import "./globals.css";
import FooterExtra from "@/components/FooterExtra";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const ibmPlexSerif = IBM_Plex_Serif({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ibm-plex-serif",
});
export const metadata: Metadata = {
  title: "BankTransfer",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${ibmPlexSerif.variable} antialiased h-screen flex flex-col overflow-hidden`}
      >
        {/* contenido */}
        <main className="flex-1 min-h-0 overflow-auto pb-14">{children}</main>

        {/* footer */}
        <div className="shrink-0">
          <FooterExtra />
        </div>
      </body>
    </html>
  );
}
